# Use new container infrastructure to enable caching
sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    packages:
      - libgmp3-dev
      - python-docutils

before_script:
  - ./generate-stack-yaml.hs
  - stack --no-terminal setup

  # Prebuild this dependency separately because building it takes a lot of memory.
  # It has caused me out-of-memory errors on Travis several times.
  - stack build -j 1 haskell-src-exts

  - stack --no-terminal build

script: stack exec diagrams-doc -- buildh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#diagrams"
    skip_join: true
    template:
      - "\x0313diagrams-doc\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
