resolver: lts-5.13
packages:
- '.'

# Use git version of docutils because docutils is not on Hackage or Stackage
- location:
    git: https://github.com/diagrams/docutils
    commit: 1850209065225b5f2dc70da0574629ce14463e58

# Use git version of diagrams-builder because Hackage and Stackage
# versions don't have `qimports` function
- location:
    git: https://github.com/diagrams/diagrams-builder
    commit: 30f93fe920102acb1149f244108331f467d972a7

# 18 Mar 2016
- location:
    git: https://github.com/diagrams/diagrams-lib
    commit: 831ec8c9208d96ce5ab6e58a9b5510e2dcfbb900

# 19 Feb 2016
- location:
    git: https://github.com/diagrams/diagrams-core
    commit: b9031972c22960fc104aa50100619e3337bc7c09

- location:
    git: https://github.com/diagrams/diagrams-solve
    commit: d35a53399db4c1d4a15b6bb7bde2d6229a53feb6

- location:
    git: https://github.com/diagrams/active
    commit: fa47a0a777cead800c2c6a524de3db8138a1130f

- location:
    git: https://github.com/diagrams/statestack
    commit: f7c76b1b0c05f3fc43c3092d8bf1698fb8ab9e9a

- location:
    git: https://github.com/diagrams/dual-tree
    commit: fd6d4eaf707497255dcbd13aaa94d95ecc9139c5

- location:
    git: https://github.com/diagrams/monoid-extras
    commit: fdb1ac417bb76ae9d5c70842790a93311720d42c

# 30 Nov 2015
- location:
    git: https://github.com/diagrams/diagrams-rasterific
    commit: 1fa7c3d4393e993e89803adf11a6b6d90fffd80d

extra-deps:
# These dependencies are currently on stackage nightly,
# they might make it in to lts-5.14
- tuple-0.3.0.2
- OneTuple-0.2.1
- SVGFonts-1.5.0.0
flags: {}
# flags:
#   diagrams-doc:
#     UseSVG: true
extra-package-dbs: []
